- meta:
    map: test
    node: WayPoint0
    pointset: test
  node:
    edges:
      - action: move_base
        edge_id: WayPoint0_WayPoint3
        inflation_radius: 0.0
        map_2d: cropped
        node: WayPoint3
        recovery_behaviours_config: ""
        top_vel: 0.55
    localise_by_topic: ""
    map: test
    name: WayPoint0
    pointset: test
    pose:
      orientation:
        w: 1.0
        x: 0.0
        y: 0.0
        z: 0.0
      position:
        x: -84.0
        y: -5.5
        z: 0.0
    # verts:
    # - x: -84.0
    #   y: -5.5
    # - x: -77.6
    #   y: -25.1
    # - x: -71.0
    #   y: -40.2
    # - x: -60.4
    #   y: -65.0
    xy_goal_tolerance: 0.3
    yaw_goal_tolerance: 0.2
- meta:
    map: test
    node: WayPoint1
    pointset: test
  node:
    edges:
      - action: move_base
        edge_id: WayPoint1_WayPoint0
        inflation_radius: 0.0
        map_2d: cropped
        node: WayPoint0
        recovery_behaviours_config: ""
        top_vel: 0.55
      - action: move_base
        edge_id: WayPoint1_WayPoint4
        inflation_radius: 0.0
        map_2d: cropped
        node: WayPoint4
        recovery_behaviours_config: ""
        top_vel: 0.55
      - action: move_base
        edge_id: WayPoint1_WayPoint5
        inflation_radius: 0.0
        map_2d: cropped
        node: WayPoint5
        recovery_behaviours_config: ""
        top_vel: 0.55
    localise_by_topic: ""
    map: test
    name: WayPoint1
    pointset: test
    pose:
      orientation:
        w: 1.0
        x: 0.0
        y: 0.0
        z: 0.0
      position:
        x: -77.6
        y: -25.1
        z: 0.0
    xy_goal_tolerance: 0.3
    yaw_goal_tolerance: 0.2
- meta:
    map: test
    node: WayPoint2
    pointset: test
  node:
    edges:
      - action: move_base
        edge_id: WayPoint2_WayPoint1
        inflation_radius: 0.0
        map_2d: cropped
        node: WayPoint1
        recovery_behaviours_config: ""
        top_vel: 0.55
      - action: move_base
        edge_id: WayPoint2_WayPoint3
        inflation_radius: 0.0
        map_2d: cropped
        node: WayPoint3
        recovery_behaviours_config: ""
        top_vel: 0.55
      - action: move_base
        edge_id: WayPoint2_WayPoint5
        inflation_radius: 0.0
        map_2d: cropped
        node: WayPoint5
        recovery_behaviours_config: ""
        top_vel: 0.55
    localise_by_topic: ""
    map: test
    name: WayPoint2
    pointset: test
    pose:
      orientation:
        w: 1.0
        x: 0.0
        y: 0.0
        z: 0.0
      position:
        x: -71.0
        y: -40.2
        z: 0.0
    xy_goal_tolerance: 0.3
    yaw_goal_tolerance: 0.2
- meta:
    map: test
    node: WayPoint3
    pointset: test
  node:
    edges:
      - action: move_base
        edge_id: WayPoint3_WayPoint4
        inflation_radius: 0.0
        map_2d: cropped
        node: WayPoint4
        recovery_behaviours_config: ""
        top_vel: 0.55
    localise_by_topic: ""
    map: test
    name: WayPoint3
    pointset: test
    pose:
      orientation:
        w: 1.0
        x: 0.0
        y: 0.0
        z: 0.0
      position:
        x: -60.4
        y: -65.0
        z: 0.0
    verts:
      - x: 0.689999997616
        y: 0.287000000477
      - x: 0.287000000477
        y: 0.689999997616
      - x: -0.287000000477
        y: 0.689999997616
      - x: -0.689999997616
        y: 0.287000000477
      - x: -0.689999997616
        y: -0.287000000477
      - x: -0.287000000477
        y: -0.689999997616
      - x: 0.287000000477
        y: -0.689999997616
      - x: 0.689999997616
        y: -0.287000000477
    xy_goal_tolerance: 0.3
    yaw_goal_tolerance: 0.2
