services:
  ros-noetic:
    build:
      context: .
      dockerfile: Dockerfile
    image: ros-noetic-gantry-dev
    container_name: ros_noetic_gantry_container
    stdin_open: true
    tty: true
    command: /bin/bash
    network_mode: host
    privileged: true
    devices:
      - /dev:/dev
    environment:
      - BASE_WS=/home/ros/base_ws
      - DISPLAY=${HOST_DISPLAY_VAR:-:0}
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ../ros_ws_src:/home/ros/catkin_ws/src:rw
      - ../bash_scripts:/home/ros/bash_scripts:rw
